### ISSUE TITLE
Cannot open files with Hex Editor extension

### ISSUE THREAD

**Issue by sjdhome** [fython/vscode-gwo-android-helper#1]
![屏幕截图 2021-02-21 194812](https://user-images.githubusercontent.com/11871061/108624135-e06e6f80-747d-11eb-9a1f-dc71f4832124.png)
不知道是Hex Editor的问题还是这边的问题。

**Comment by fython** [comment]
> [microsoft/vscode-hexeditor:src/fileSystemAdaptor.ts#L27-L37](https://github.com/microsoft/vscode-hexeditor/blob/21c1111efa167416db972b7f74e1f8985458ed6f/src/fileSystemAdaptor.ts#L27-L37)

```typescript
  public static async readFile(uri: vscode.Uri): Promise<Uint8Array> {
    if (uri.scheme === "untitled") {
      const document = FileSystemAdaptor.findMatchingTextDocument(uri);
      // Conver the document text to bytes and return it
      return document ? new TextEncoder().encode(document.getText()) : new Uint8Array();
    } else if (uri.scheme === "file") {
      return vscode.workspace.fs.readFile(uri);
    } else {
      throw `Unsupported URI scheme ${uri.scheme}`;
    }
  }
```

Hex Editor 扩展只允许访问 VS Code 内置的 `untitled` 和 `file` scheme uri，从 VS Code API 文档上看现在是支持其他扩展访问额外支持的文件系统，可能历史遗留代码没有加上支持。

HexEditor allows to access VS Code bulit-in scheme uri `untitled` and `file` only. According to VS Code API documentation, this API (`vscode.workspace.fs`) can access interface exposed by other extensions' contributed file system providers.

**Comment by fython** [comment]
@sjdhome [microsoft/vscode-hexeditor](https://github.com/microsoft/vscode-hexeditor) 主分支已经合并了我的 fix 提交，目前还没有发版，如有需要可以自行编译，此 Issue 将关闭。

[microsoft/vscode-hexeditor](https://github.com/microsoft/vscode-hexeditor) main branch has merged my commit to fix. Currently, it hasn't been released. If you need this patch, you can compile `vscode-hexeditor` by yourself. This issue will be closed.
