### ISSUE TITLE
Not compatible my vscode version 1.52.1

### ISSUE THREAD

**Issue by lori-zhao** [fython/vscode-gwo-android-helper#2]
![image](https://user-images.githubusercontent.com/22452283/109292818-e8efed00-7865-11eb-86ff-157a915d2bc5.png)
install gwo-android-help error
can not install  gwo-android-help error
because it is not compatible with vscode 1.52.1

Do i need to update？

**Comment by fython** [comment]
@ZhaoSiBo Maybe API used by this extension is available in VSCode 1.52.1 or older version. But I wrote `1.53` required at `package.json`.

The better way is to upgrade your VSCode to latest version (release channel). If you have any reason to prevent from upgrading VSCode, feel free to share it.

**Comment by lori-zhao** [comment]
Thanks for your answer, it works normally
![image](https://user-images.githubusercontent.com/22452283/109446042-dfd86900-7a7b-11eb-9276-0fc220278f12.png)
